### ISSUE TITLE
Windows 32 bit SVN repository url is wrong.

### ISSUE THREAD

**Issue by Zeejfps** [TylerGubala/bpy-build#1]
The build fails because the script tries to download the dependancies from:
https://svn.blender.org/svnroot/bf-blender/trunk/lib/win32_vc14/
when it should be:
https://svn.blender.org/svnroot/bf-blender/trunk/lib/windows_vc14/

Working on a pull request right now.

**Comment by TylerGubala** [comment]
Your pull request worked for me so I'm closing this issue until a new one arises.

On my personal roadmap is to change the way that blenderpy installs the module; currently the files are untracked by pip (they __cannot__ be uninstalled by pip as it is currently and must be removed manually)

This will therefore change quite a bit about how the module is built and thusly the ```bpy-build``` module may go away entirely. So heads up on that, I guess.
