### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by mcgeo52** [TylerGubala/bpy-build#10]
pip install bpy && bpy_post_install

results in:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-y1jbk_c2/bpy/

**Comment by TylerGubala** [comment]
Could you please post you operating system and Python version?

Looks like Linux. If that is the case, then you have the option of installing from `wheel` off [my google drive location](https://drive.google.com/drive/folders/1uSiTQLvlUxu7PDT2TCT4XIrwGwn1WWph?usp=sharing)

**Comment by mcgeo52** [comment]
ubuntu 18.04, Python 2.7.17

**Comment by ebby123** [comment]
iirc error code 1 is your side

**Comment by TylerGubala** [comment]
@ebby123 I'm not sure what you mean.

@mcgeo52 `bpy` does not support Python 2.7
