### ISSUE TITLE
Migrate build code to bpy-make

### ISSUE THREAD

**Issue by TylerGubala** [TylerGubala/bpy-build#4]
`bpy-make` is my upcoming module that promises to support the build process for all versions of Python >=3.4

The reason for migrating out the build code from this repo is that wrangling imports in `setup.py` is really quite difficult. Currently, I would have to import `git`, `svn` and `cmake` modules for the majority of the build process in `bpy-build`s setup routine, which is a real hassle since it has to be imported every function.

`bpy-make` will be the only thing to import once it is finished and will take care of traversing the `blender` `git` and `svn` releases, checking for which one is valid for the requested api and Python version.

This will also fix the weirdness of the svn Python version being used; we will grab the appropriate python version off the svn libraries as we find them

**Comment by jl-DaDar** [comment]
where is bpy-make?

**Comment by TylerGubala** [comment]
`bpy-make` is no longer necessary, so it does not exist any more. I was able to migrate all of the code I generated in `bpy-make` back into `bpy-build` anyways and achieved the same level of separation in the build script anyways, so I got rid of `bpy-make`.
